/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_memhog_NativeHogLib */

#ifndef _Included_com_nokia_memhog_NativeHogLib
#define _Included_com_nokia_memhog_NativeHogLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_memhog_NativeHogLib
 * Method:    Swallow
 * Signature: (I)Z
 */
JNIEXPORT jint JNICALL Java_com_nokia_memhog_NativeHogLib_Swallow
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_memhog_NativeHogLib
 * Method:    Shit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nokia_memhog_NativeHogLib_Shit
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_memhog_NativeHogLib
 * Method:    HowFat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_memhog_NativeHogLib_HowFat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
